Sylius/Sylius-Standard

- app/config/parameters.yml.dist
Added parameter    sylius.currency_importer.ecb.base_currency: EUR (parameter.yml.dist)
This missing parameter causes install failure.
> Fix issue 1 - Corrected parameter.yml.dist

- app/config/config.yml
Same as symfony-standard (https://github.com/symfony/symfony-standard/blob/2.8/app/config/config.yml#L30). 
Fixes https://github.com/Sylius/Sylius/issues/2585.
> Session handler config fix

- composer.json
|  Q | A |
|---|---|
|  Fixed Tickets | #123 |
|  License | MIT |
Just remove the commands from the composer.json to make the warning dissapear.
> Remove CMF commands from composer as they are not present

- .travis.yml
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
PHP 7.1 was released yesterday, so I think it's about time to run the test suite against it 🎉 
Build is failing for 7.1 because of `Warning: A non-numeric value encountered  in ...` which is fixed in https://github.com/Sylius/Sylius/pull/6757
> [Travis] Enable PHP 7.1 for tests

- .gitignore
As described in the readme file, server:start should be used to start a webserver for Sylius.
This will make the command create a .web-server-pid file, which is not covered by .gitignore.
> Add server:start pid file to .gitignore

- package.json
- yarn.lock
| Branch?         | 1.0
| Bug fix?        | yes?
| New feature?    | no
Node.js 10 compatibility was introduced in node-sass [v4.9.0](https://github.com/sass/node-sass/releases/tag/v4.9.0)
Maybe we could revert #222 after this is merged?
> Update node-sass for compatibility with Node.js 10

- gulpfile.babel.js
| Branch?         | 1.2
| New feature?    | no
Since it was unnecessarily added in #228, and not properly implemented anyway.
> Remove vendorPath command-line argument from root gulpfile

- .travis.yml
Changes made:
- default test suite put into stages
- run default stage suite without sudo
- run Docker with sudo required
- use mysql & memcached services only in default stage
- use docker only in docker stage
It also removes the need for `after_success: true` placeholders and provides better stage separation.
> Tweak Travis CI config

- docker-compose.yml
The correct build order is important for proper Docker layer caching.
> Fix Docker image build order

- Dockerfile
When building the `php` image, the following error appears:
```shell
+ nproc
/bin/sh: nproc: not found
+ docker-php-ext-install -j exif gd intl pdo_mysql zip
make: the '-j' option requires a positive integer argument
```
It's because `nproc` is not available in the `php-fpm-alpine` image but can be found in the `coreutils` package: https://pkgs.alpinelinux.org/contents?file=nproc&path=&name=&branch=edge
I've added it to the `build-deps` in order to fix it.
> Fix: add coreutils to build-deps to be able to use nproc

- docker-compose.yml
- docker/php/php-cli.dev.ini
| Branch?         | 1.3 (or master?)
| New feature?    | no?
Because memory usage should be under control in `prod`.
> Only change php memory_limit in dev for Docker

- composer.json
`sensiolabs/security-checker` is needed for `auto-scripts` so when you put it in production you will get errors because this package does not exists.
Bug #296
> Wrong dev package placement

- config/packages/security.yaml
The same should be done for `1.4`, I believe it can be a problem for not being able to log in to the administration panel just after the installation (but I've checked it on `1.4`, so I don't know does it happen also for `1.3`):
> Synchronize security.yaml with Sylius/Sylius

- composer.json
Using [@php](https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts) in composer.json to resolve in a path to the PHP process is currently being used.
Resolve issues in the environments where are multiple PHP versions used.
> [Composer] Update path to PHP binary in scripts

- config/bootstrap.php
Fixes this notice: `The default value of "$usePutenv" argument of "Symfony\Component\Dotenv\Dotenv::__construct" will be changed from "true" to "false" in Symfony 5.0. You should define its value explicitly.`
> Fix deprecation notice

- .gitignore
On fresh copy, there are no ability to list commands and run some other commands until sylius:install will be executed (which will create public/media/image directory)
Ref. https://github.com/Sylius/Sylius/pull/9961
> [Config] Add missing media image folder

- docker-compose.yml
Avoid problem with permissions as the mailhog container does not run as root
> Don't mount mailhog maildir directory from host

- assets/admin/entry.js
- assets/shop/entry.js
- package.json
- webpack.config.js
- yarn.lock
1. Install webpack-encore-bundle
```
composer require symfony/webpack-encore-bundle
```
2. Edit `config/packages/assets.yaml` file
```yml
framework:
assets:
packages:
shop:
json_manifest_path: '%kernel.project_dir%/public/build/shop/manifest.json'
admin:
json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
```
3. Edit `config/packages/webpack_encore.yaml` file
```yml
webpack_encore:
output_path: '%kernel.project_dir%/public/build/default'
builds:
shop: '%kernel.project_dir%/public/build/shop'
admin: '%kernel.project_dir%/public/build/admin'
```
4. Overwrite template files with new assets paths
```js
// templates/bundles/SyliusAdminBundle/_scripts.html.twig
{{ encore_entry_script_tags('admin-entry', null, 'admin') }}
```
```js
// …
```
> Add Webpack config

- config/packages/dev/security_checker.yaml
- config/packages/test/security_checker.yaml
- config/packages/test_cached/security_checker.yaml
This config is not needed anymore, as related library was removed here: https://github.com/Sylius/Sylius-Standard/commit/c8922aa2253cba2ba559bbad9d2bbfb820b779b2#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L44
> [Maintenance] Remove security checker config

- .travis.yml
- composer.json
- composer.lock
- src/Migrations/Version20200916093101.php
- symfony.lock
I've removed the platform from the composer to let flex detect the current environment based on used CLI PHP. In addition, I've added composer v2
Replacecment for #434
> [Maintenance] Remove php platform from composer

- composer.lock
During the previous build, I was missing an update of composer.lock and upgrade of PayPal Plugin to v1.0.3. It worked, because Travis is using `composer update` instead of `composer install`, but it will install different packages in CI and after `composer create-project`.
> [Composer] Update sylius deps

- .github/workflows/build.yml
In the coming weeks, ubuntu-latest will start pointing to ubuntu-20.04 instead of ubuntu-18.04. Let's prevent potential failures by specifying directly ubuntu-18.04 for now and consiously upgrading to ubuntu-20.04 when we're ready - possibly after dropping PHP 7.3 compatibility, since setting it up on the newer version of Ubuntu takes a lot more time.
Ref: https://github.com/actions/virtual-environments/issues/1816
> [CI] Switch from ubuntu-latest to ubuntu-18.04

- .github/auto-merge.yml
- .github/workflows/auto-merge.yml
Using this action has some strong advantages over the previous bot:
* detects Dependabot PRs automatically (relying on the label name is a little bit silly approach)
* automatically approve PRs if it fulfils the requirements
* we're able to configure that only minor upgrades would be merged
🤞 it will work 🚀
> Auto-merge dependabot PRs with Github Actions

- .github/workflows/build.yml
Apps based on Sylius-Standard are not published anyway.
> [CI] Add --no-check-publish to Composer validation

- public/.htaccess
Actually, there is no protection against click-jacking. Given the nature of the platform (credentials, credit cards informations ecc) i think that this should be the default behavior.
What do you think?
Doc reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
> Prevents click jacking

- config/packages/framework.yaml
This would become necessary if someone would like to modify serialization for api.
> Add serialization mapping to framework.yaml

- config/packages/doctrine.yaml
- config/packages/prod/doctrine.yaml
- config/packages/test_cached/doctrine.yaml
It breaks the application when DoctrineBundle v2.4.0+ is used. See https://github.com/doctrine/DoctrineBundle/pull/1356.
> Fix Doctrine config

- config/packages/security.yaml
Ref: https://twitter.com/mbabker/status/1405962888792231939?s=21 and https://github.com/liip/LiipImagineBundle/pull/1383
Most apps don't need authenticated user info when resolving images, so we can sanely disable the security authentication for these routes.
> Disable auth for LiipImagineBundle controllers

- Dockerfile
- docker/php/docker-entrypoint.sh
Updating the default versions in the Dockerfile.
The composer dependencies listed by Sylius standard no longer support PHP 7.3 and the NodeJS + nginx versions are heavily outdated.
Upgrading NodeJS even further can be done, but requires a lot more work as the front end dependencies are also pretty outdated. So I'd suggest doing it in a separate PR or development cycle.
Please don't just tag this and leave it hanging, currently the Docker setup is unusable because of this.
Perhaps we should add a step to the github actions workflow to check and confirm that the container images can actually be built, or even better build them and use them in the workflow. What do you think about that?
> Update php, nodejs and nginx in Dockerfile

- docker/nginx/conf.d/default.conf
I think https://github.com/Sylius/Sylius-Standard/pull/536 has introduced a little error https://github.com/Sylius/Sylius-Standard/pull/536/files#diff-f583d11fcce9311b02b20054d21bc42d9c3ce8337322f0f4c66a16f36825f766R12-R13
> Fix inverted line in nginx configuration

- docker/php/php-cli.ini
The last release has required me to increase memory_limit to 3G on branch master on my two computers.
This is the last problem I had with the new docker setup. Maybe rebasing and merging this PR would be cool before release, especially the healthcheck https://github.com/Sylius/Sylius-Standard/pull/391
ping @lchrusciel
> Increase PHP memory_limit for cli

- composer.json
- config/services_test.yaml
- src/Kernel.php
Sylius 1.10.6 release has broken running the app based on the Sylius-Standard in a test environment. It's caused by [moving `"polishsymfonycommunity/symfony-mocker-container"` to `require-dev`](https://github.com/Sylius/Sylius/commit/673bc6662c3934f3e5c1e8cfa0a3fc8710a437b1#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34). `polishsymfonycommunity/symfony-mocker-container` is no longer being downloaded so it throws error because in test env it is used in `src/Kernel.php`.
> Add missing polishsymfonycommunity/symfony-mocker-container dependency

- Dockerfile
Recent alpine updates require python 2 to be installed as `python3` package, otherwise image build fails.
> Update python package name in nodejs step

- .env
- .env.test
- .env.test_cached
- .github/workflows/build.yml
- behat.yml.dist
- config/packages/test_cached/web_profiler.yaml
Content of PR:
- Changes to PHP, Node and Sf versions
- Usage of sync messenger transport in testing required for proper testing results
- Temporary removal of schema validation waiting for the Sylius release after: https://github.com/Sylius/Sylius/pull/13214
- Whitespace removal in Behat tags - could be omitted, as it is minor stuff, but deprecation error was driving me nuts
- Due to some strange issue with test test execution(ref. https://github.com/Sylius/Sylius-Standard/actions/runs/1688323707) the [vendor/sylius/sylius/features/promotion/managing_catalog_promotions/toggling_catalog_promotion.feature:35](https://github.com/Sylius/Sylius/blob/54dcc4f2ed0a4fea5908fbea3bd69a0f27f16fa1/features/promotion/managing_catalog_promotions/toggling_catalog_promotion.feature#L35-L40) scenario …
> [Maintenance] Fix build & prepare it for Sylius v1.11

- composer.json
~~This updates composer.json to match the requirements in Sylius/Sylius master: PHP `^8.0` and Symfony `^5.4`.~~
~~Also adds a the `extra/symfony/require` element with the value of `^5.4`. This will mean that whenever `composer require symfony/whatev` is issued, it will automatically require `^5.4` when possible, so you won't end up with a mix of packages from 5.4 and 6.x.~~
~~Also bumps `symfony/flex` requirement to `^2.0` (fixes #645).~~
This updates composer.json to require PHP ^8.0.
Also changes `dev-master` branch alias to `1.11-dev` (fixes #635). Although maybe that should already be changed to `1.12-dev` instead?
> Upgrade required version of PHP to 8.0

- .github/workflows/build.yml
- composer.json
This is a spin-off from #659 and includes #659.
It updates composer.json:
1. All Symfony packages which currently require v4.4 or v5.x will now require `^5.4`.
2. The `extra/symfony/require` element is added with the value of `^5.4`. This will mean that whenever `composer require symfony/*` is issued, it will automatically require `^5.4` when possible, so you won't end up with a mix of packages from 5.4 and 6.x.
3. `symfony/flex` requirement bumped to `^2.1` (contains #661 and deprecates #645).
> Drop symfony4 support

- Dockerfile
Revert of #643. It is still needed due to node and gyp dependency
> [Docker] Bring back python2 dep

- config/packages/dev/_sylius.yaml
For easier development of testing of the new application 🖖 It was already done for Sylius/Sylius [a long time ago](https://github.com/Sylius/Sylius/pull/12804).
> Enable Sylius API in dev by default

- .env
The current mailing config results in 500 errors - this is the result that we can be sure of. So, it is better to turn it off by default, in my humble opinion. People who need mailing will adjust it anyway. The rest won't have a broken website. 
The second config is quite similar. This is our recommendation, so it is reasonable to have it there.
> [README] Add reasonable defaults configs for mailing and messenger to avoid production errors

- .github/workflows/build.yml
- behat.yml.dist
This removes the deprecation warning about the whitespace when running Behat.
> Remove deprecated whitespace from tag filter

- Dockerfile
During an installation the composer asks for plugins (https://getcomposer.org/doc/06-config.md#allow-plugins) that leads to failing Docker build and making the terminal interactive.
How to reproduce the problem? Create a project from current Sylius-Standard and try to run `docker compose up -d`
> [Docker]Force no-interaction mode on installation

- docker-compose.yml
MySQL supports only amd64 architecture therefore without defining a platform the docker-compose fails on image download.
> [Docker]Define MySQL platform as linux/amd64

- docker-compose.prod.yml
- docker-compose.yml
The Docker Compose `version` is optional and there is no value to keeping that as the latest specification is just a "Compose Specification" instead of value-versioning https://docs.docker.com/compose/compose-file/
More to read in Docker Compose versioning reference: https://docs.docker.com/compose/compose-file/compose-versioning/
Current Docker Compose version: v2.4.1
> [docker]Remove Docker Compose optional version

- Dockerfile
- docker-compose.yml
The Dockerfile is "production oriented", yet it specifies the default command as `yarn watch` which executes a process of actively looking for changes. We don't need to do that in the production environment as the purpose of the node container would be to build and store assets and media files.
To maintain development environment the `yarn watch` command was specified in the `docker-compose`
> [docker]Execute yarn build in production Dockerfile

- .github/workflows/build.yml
- composer.json
- package.json
From time to time, the last released version is not enough on master here. Some changes we would like to prepare in advance like #690. 
^1.12@dev makes the most sense to me - it is clear, that we are working on the development of v1.12, but accepting dev-master. 
Ref. https://semver.madewithlove.com/?package=sylius%2Fsylius&constraint=^1.11&stability=dev (but for version 1.11 to see how it behaves)
> [Maintenance] Update Sylius to newest dev master

- docker-compose.yml
The images some time ago (2018) were pointing to the `quay.io/sylius/XYZ:latest` images, now they are pointing to the official images that do not make sense in this type of building docker compose.
> [docker]Do not download images as they don't exist

- docker-compose.prod.yml
- docker-compose.yml
The Percona was introduced in the docker-compose in 2018, but we officially do not support this database provider (even if it is MySQL-based db engine)
> [docker]Use mysql instead of percona

- .github/workflows/build.yml
We test and maintain Node 16 and 14 on Sylius/Sylius repository. Therefore it would be nice to have it tested in the project template too.
Add node 16 version to the pipeline matrix and update the setup-node action to the latest version.
> [maintenance]Enable Node 16 test pipelines

- .github/workflows/auto-merge.yml
I asked myself why the https://github.com/Sylius/Sylius-Standard/pull/734 PR is failing and that's probably because of an invalid config specified for the Dependabot.
Watch the Input section. Default config differs from `.github/dependabot.yml` https://github.com/ahmadnassri/action-dependabot-auto-merge#inputs
> [maintenance]Specify config param to auto-merge pipeline

- .github/autolabeler.yml
Same as in Sylius/Sylius auto labeling is nice automation. At this moment I don't know what kind of bot we use for auto labeling.
EDIT. I enabled https://github.com/apps/probot-autolabeler for Sylius-Standard
> [maintenance]Create autolabeler config for Sylius-Standard

- README.md
Reverts Sylius/Sylius-Standard#742
It works only for images hosted on github.
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
> Revert "[maintenance]Try dark and light Sylius logo variants"

- .env.prod
- docker-compose.prod.yml
1. The Docker "bridge" network is the default even without specified, but I personally think that even this should be specified.
2. Previous config required to set MYSQL_ROOT_PASSWORD and MYSQL_PASSWORD which doesn't make sense. Let's just not use the root MySQL user and everyone will be happy. Security stonks 📈
> [docker]Simplify docker-compose production environment config

- Dockerfile
The https://github.com/mlocati/docker-php-extension-installer is highly popular in the docker and PHP community because it does one very good thing - simplify the installation of PHP extensions and their dependencies.
Should we at Sylius care about what alpine package install to have PDO extensions enabled? In my opinion no.
> [docker]Use mlocati/php-extension-installer to simplify Dockerfile

- docker-compose.prod.yml
- docker-compose.yml
It's just simpler to run docker execute commands with names like node instead of `sylius-standard_node`
> [docker]Get back container names

- .dockerignore
- .github/workflows/docker.yml
- docker-compose.yml
- docker/php/docker-entrypoint.sh
- docker/test.sh
The pipeline will build Sylius Store from `docker-compose.yml` and `docker-compose.prod.yml`, but only on the linux/amd64 platform as there is no functionality to override platform from the command nor does GitHub provide ARM runners.
> Pipeline that will test Sylius Store on Docker

- Dockerfile
As far as I see the usage of Dockerfile we don't need installed mariadb-client out of the box
> [docker]Remove mariadb-client

- .dockerignore
- Dockerfile
This PR will fix the [hadolint](https://github.com/hadolint/hadolint) warning stated below.
```
Dockerfile:20 DL3022 warning: `COPY --from` should reference a previously defined `FROM` alias
Dockerfile:24 DL3022 warning: `COPY --from` should reference a previously defined `FROM` alias
```
> [docker]Hadolint improvements
