Sylius/Sylius-Standard

app/config/routing.yml
app/config/security.yml
composer.json

- Updates Sylius to v0.15.x
- Removes FOS User Bundle dependency
- Changes Security config to use SyliusUserProvider

Update to Sylius v0.15.0

---

app/config/parameters.yml.dist

Related to https://github.com/Sylius/Sylius/pull/2943.

Make path to wkhtmltopdf configurable

---

.gitignore
.travis.php.ini
.travis.yml
app/SymfonyRequirements.php
composer.json
composer.lock

Fixes Sylius/Sylius#3665, Sylius/Sylius#3644, Sylius/Sylius#3595, #79, #77.

Updated Composer & Travis

---

app/config/config.yml
app/config/config_dev.yml
app/config/routing.yml
app/config/security.yml

Fixes https://github.com/Sylius/Sylius-Standard/issues/89.

Update configuration files

---

composer.json
composer.lock

Fixes https://github.com/Sylius/Sylius-Standard/issues/92 and https://github.com/Sylius/Sylius/issues/4843.

Update sylius to the newest version

---

behat.yml.dist
composer.json
composer.lock

It will allow to remove the extension code from Sylius main repository.

Use FOB SuiteSettingsExtension

---

.travis.yml
Gulpfile.js
composer.json
composer.lock

This PR consist of three commits from https://github.com/Sylius/Sylius-Standard/pull/106. I've decided to apply them separately, to better debug some nasty errors from mentioned PR.
> BEWARE
I've encounter a really annoying problem with one feature. It's excluded for now to not stop development process (as master build is failing and should be fixed asap) but i surely should be repaired **as soon as possible** (either here or on *Sylius/Sylius*).

Master build fix

---

app/config/security.yml
composer.lock

Fixes issue reported in Sylius/Sylius#5796

Updated security.yml to support new multi-user providers

---

package.json

Add scripts gulp:gulp in package.json

gulp:gulp in package.json

---

app/console

| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | Sylius/Sylius#6780 |
| License         | MIT |

Use default Symfony env naming

---

app/config/config_test.yml

See https://github.com/Sylius/Sylius/issues/6897. 
Related PR at https://github.com/Sylius/Sylius/pull/6898/,

Removed unused param

---

.travis.yml

Fixes https://github.com/Sylius/Sylius-Standard/issues/110

Remove hack

---

app/Resources/TwigBundle/views/Exception/error404.html.twig
composer.json
composer.lock

Implemented changes from https://github.com/Sylius/Sylius/pull/7033

Display custom 404 page from ShopBundle

---

app/Resources/TwigBundle/views/Exception/error.html.twig
app/Resources/TwigBundle/views/Exception/error500.html.twig
composer.lock

According to changes from https://github.com/Sylius/Sylius/pull/7075

[Shop] Custom errors pages

---

app/config/config.yml
app/config/parameters.yml.dist

Clean up parameters

---

app/config/config.yml
app/config/config_test.yml
app/config/config_test_cached.yml
composer.lock

Upgrades Sylius standard for https://github.com/Sylius/Sylius/pull/7349

Upgrade to latest sylius + deps + fos rest bundle

---

app/config/security.yml

Outdated security configuration.

[App] Update security configuration

---

app/config/config.yml

See https://github.com/Sylius/Sylius/issues/8372.

Update config.yml to use the parameter for db driver

---

.travis.yml

It's PHP 7.1

---

app/config/config.yml

This parameter will prevent doctrine exceptions when creating database for the first time

[Doctrine] Missing server version

---

app/config/parameters.yml.dist
composer.json
composer.lock

It was super annoying.
Fixes #182

[Composer] Use correct parameters.yml.dist

---

app/config/security.yml

Fixes https://github.com/Sylius/Sylius-Standard/issues/196

[Config] Synchronize security.yml with Sylius

---

package.json
yarn.lock

[Yarn] Allow jQuery 3.2

---

app/AppKernel.php

Bring back AppBundle to AppKernel

---

.travis.yml
app/config/config.yml
composer.json
composer.lock

Update to Sylius v1.2.0-BETA

---

gulpfile.babel.js
package.json
src/AppBundle/gulpfile.babel.js

| Branch?         | 1.2 (or master?)
| New feature?    | yes
/cc @pamil

Add gulpfile for app (AppBundle)

---

composer.json

Highly inspired by @rubenrua solution made in #254.

Use Flex's symfony-require to improve performance

---

Dockerfile
docker/php/docker-entrypoint.sh

| Branch?         | 1.3
| Bug fix?        | yes
| New feature?    | no

Fix SYMFONY_ENV -> APP_ENV in Dockerfile

---

.dockerignore
Dockerfile

| Branch?         | 1.3 (or master?)
| New feature?    | no?

Copy only specifically what we need in Dockerfile

---

docker-compose.yml
docker/nginx/conf.d/default.conf
docker/php/php-cli.dev.ini
docker/php/php.ini

| Branch?         | 1.3 (or master?)
| New feature?    | no?
#277 should be merged before this, as it introduces a new file which we modify here.

 Increase upload file size limit for Docker

---

config/packages/_sylius.yaml

See https://github.com/Sylius/Sylius/issues/9807 for the details. Fixes #278.

Change the theme directory from "app/themes/" to "themes/"

---

composer.json
composer.lock

Move Flex from "require-dev" to "require"

---

.travis.yml
app/TestAppKernel.php

changes incorporated from https://github.com/Sylius/Sylius/pull/10067

Remove container cleanup in test environment (1.2)

---

app/TestAppKernel.php
app/config/config_test.yml
app/config/config_test_cached.yml
app/config/routing_test.yml
app/config/routing_test_cached.yml
composer.json
composer.lock

Replaces https://github.com/Sylius/Sylius-Standard/pull/320
I've installed again `stripe/stripe-php` which was removed in https://github.com/Sylius/Sylius-Standard/pull/311... but the build was failing, I don't know why 🐰

Fix the build vol.2

---

docker-compose.yml

Mailhog was not working out of the box for me.
This fixes it. (Or is there a better way to enable mailhog for development?)

[Docker] Set the mailer to use the mailhog container

---

docker-compose.yml

According to https://github.com/Sylius/Sylius-Standard/pull/334#discussion_r302146028.

Do not expose Mailhog 1025 port to the host

---

composer.json

Colorize inform about GUS command

---

.editorconfig

The file in `Sylius/Sylius-Standard` differs from the one in `Sylius/Sylius` which I guess doesn't make sense

Sync file with Sylius/Sylius

---

composer.json
composer.lock
config/packages/doctrine_migrations.yaml
config/packages/security.yaml
config/packages/sylius_labs_doctrine_migrations_extra.yaml
symfony.lock

As mentioned in https://github.com/SyliusLabs/DoctrineMigrationsExtraBundle/pull/5

[DX][Database] Configure default migration folder and update to Sylius 1.8.1

---

src/Entity/Order/Adjustment.php

fix for changes related to https://github.com/Sylius/Sylius/pull/12116

fix for new adjustment migration

---

public/index.php

Apparently, we missed a thing 😄 💃

[Debug] Replace Debug class to make Sylius work again

---

config/routes/sylius_admin.yaml

Use parameter for admin route prefix

---

README.md

Copied from https://github.com/Sylius/Sylius

Update community support channels

---

README.md

New recommended way to run Symfony server

---

Dockerfile
symfony.lock
yarn.lock

```
#0 33.73 (1/1) Purging .phpize-deps-configure (20220512.104213)
#0 33.74 OK: 371 MiB in 105 packages
#0 34.00 + pecl install apcu-5.1.17
#0 96.32 Package "apcu" Version "5.1.17" does not have REST dependency information available
```

[docker]Increase APCU module version

---

.github/workflows/docker.yml

Simple pipeline docker builds that will check whether any change in any files will break docker.

[docker]Create docker build pipeline

---

README.md

https://github.com/Sylius/Vagrant

[maintenance]Remove vagrant annotation from readme

---

README.md

https://dev.to/arnavkr/using-darklight-mode-specific-images-in-github-markdown-3iln

[maintenance]Try dark and light Sylius logo variants

---

ecs.php

https://tomasvotruba.com/blog/new-in-ecs-simpler-config

[maintenance]Fix ECS config

---

Dockerfile

Slowly but steadily I remove things that are not necessary to use inside the Sylius Standard's docker.

[docker]Remove git from Dockerfile

---

README.md

I changed the readme to be more GitHub markdown syntax compatible and added the section on how to deploy and use sylius docker 🐳

[docker]Describe how to run Sylius-Standard with docker compose configuration

---

.github/workflows/docker.yml
Dockerfile

It will fix building error: https://github.com/Sylius/Sylius-Standard/runs/6811054590?check_suite_focus=true

[docker]Specify alpine version for node and php-fpm images

---

ecs.php

Similar to https://github.com/Sylius/Sylius-Standard/pull/776 but with syntax change as well 🖖

Update ECS configuration to fix the build

---

Dockerfile
docker-compose.prod.yml
docker-compose.yml

What it improves is the lack of development dependencies in the production environment.
Also, I found out that the `env_file` statement wasn't working as it should be.. therefore I decided to postpone that idea.

[docker]Create development image stage
